### ISSUE TITLE
Meteor 1.2

### ISSUE THREAD

**Issue by uzumaxy** [deamonsoft/salo#21]
Update to fresh version of the Meteor Framework

**Comment by meyginix** [comment]
All packages have been successfully updated except this: https://github.com/yogiben/meteor-admin-settings. 
Due to this issue: https://github.com/yogiben/meteor-admin-settings/issues/3, I could not update it.
Seems, package author forgot about its repo.
We need to decide what to do with this package. 
Should we use another one or implement needed functionality by ourselves.
